"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { ShoppingCart } from "react-feather";
import { QueryClient, QueryClientProvider } from "react-query";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <head>
        <title>Online Store</title>
      </head>
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <div className="flex justify-between py-5 bg-zinc-700 border-b lg:px-36 px-4 max-h-[96px]">
            <div className="flex items-center">
              <ShoppingCart size={40} className="m-2" />
              <Link
                href="/"
                className="md:text-3xl text-2xl text-center h-[30px] font-semibold"
              >
                Online Store
              </Link>
            </div>
            <Link
                href="/"
                className="md:text-3xl text-2xl text-center h-[30px] font-semibold"
              >
                <ShoppingCart size={40} classname="m-2"/>
              </Link>
          </div>
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
